### ISSUE TITLE
Add comments for each parameter in config.yaml

### ISSUE THREAD

**Issue by vfdev-5** [pytorch-ignite/code-generator#293]
Right now we can see the following in the config.yaml:
```yaml
seed: 777
data_path: ./
train_batch_size: 32
eval_batch_size: 32
num_workers: 4
max_epochs: 20
use_amp: false
debug: false
filename_prefix: training
n_saved: 2
save_every_iters: 1000
patience: 3
output_dir: ./logs
log_every_iters: 10
lr: 0.0001
model: resnet18
```
and it is unclear what each parameter is responsible for.

The idea is to add comments for each parameter like below
```
seed: 777  # random seed
data_path: ./  # input data path 
train_batch_size: 32
eval_batch_size: 32
num_workers: 4
max_epochs: 20
use_amp: false
debug: false
filename_prefix: training  # training checkpoint filename prefix
n_saved: 2  # number of saved checkpoints
save_every_iters: 1000  # training checkpoint frequency
patience: 3  # early stopping patience parameter
output_dir: ./logs  # output folder
log_every_iters: 10
lr: 0.0001
model: resnet18
```
